### ISSUE TITLE
        Error: pq: syntax error at or near "`"

### ISSUE THREAD

**Issue by millken** [ilibs/gosql#15]
``
	configs["default"] = &gosql.Config{
		Enable:  true,
		Driver:  "postgres",
		Dsn:    "...",
		ShowSql: true,
	}

	err = gosql.Connect(configs)
	_, err = gosql.Table("users").Create(map[string]interface{}{
		"username":      username,
		"status":        1,
	})
``
the log
``
        Query: INSERT INTO `users` (,`status`,`username`) VALUES(?,?);
        Args:  []interface {}{ 1, "test12345"}
        Error: pq: syntax error at or near "`"
        Time:  0.00698s
``

**Comment by fifsky** [comment]
Sorry, postgres is not compatible yet

**Comment by fifsky** [comment]
You can try v2.0.1 to try to fix qoutes compatibility problems

https://github.com/ilibs/gosql/releases/tag/v2.0.1
