### ISSUE TITLE
can where method support In query? 

### ISSUE THREAD

**Issue by Leihb** [ilibs/gosql#22]
I love this library so much, it's simple yet powerful.
It could even be better if it support "in query" in where method.

for example:
```
users := make([]*User, 0)
gosql.Model(&user).Where("id in (?)", []int{1, 2, 3}).All()

```

**Comment by fifsky** [comment]
@Leihb   Yes, This is Support

See
https://github.com/ilibs/gosql/blob/master/model_test.go#L267

**Comment by Leihb** [comment]
@fifsky thank you, it is great.
