### ISSUE TITLE
invalid connection

### ISSUE THREAD

**Issue by dmskys** [ilibs/gosql#3]
你好，用你这个gosql 有时候回出现db 错误 错误是： invalid connection 好像是连接池的某个链接被关闭了

找到原因了：
在使用go-sql-driver过程中，有时候我发现会报invalid connection的错误，这个错误产生的原因设置了空闲连接不为0时，客户端拿到连接有可能是已经被服务端关闭了，此时就会发生invalid connection，网上有些解决方案是把空闲连接数设置0，不知道设置为0跟设置为50之类的性能有什么大的区别吗？跪求大神解答！
当然这是因为服务端主动关闭了连接，因为服务端对连接的保持超时时间到了也关闭的，所以可以设置客户端连接超时时间小于服务端DB.SetConnMaxLifetime(time.Second)

https://www.studygolang.com/topics/5576
你能不能框架 修复一下这个问题 默认配置一下

sess.SetMaxOpenConns(conf.MaxOpenConns)
sess.SetMaxIdleConns(conf.MaxIdleConns)
sess.SetConnMaxLifetime(conf.MaxLifetime)

type Config struct {
	Enable       bool   `json:"enable"`
	Driver       string `json:"driver"`
	Dsn          string `json:"dsn"`
	MaxOpenConns int    `toml:"max_open_conns" json:"max_open_conns"`
	MaxIdleConns int    `toml:"max_idle_conns" json:"max_idle_conns"`
	MaxLifetime int    `toml:"max_lifetime" json:"max_lifetime"`
	ShowSql      bool   `toml:"show_sql" json:"show_sql"`
}

**Comment by fifsky** [comment]
谢谢你的建议，已经添加了该配置项，单位秒
如果有一些配置没有加入到配置文件，也可以使用如下的方式手动设置
```
gosql.DB().SetConnMaxLifetime(time.Second)
```
