### ISSUE TITLE
模型表字段为sql.nullstring时 插入掉sql出现多个字段

### ISSUE THREAD

**Issue by dmskys** [ilibs/gosql#4]
有个需求是，创建时间和成功时间，在创建的时候成功时间是可以为空的，设置表的模型为
由于我的时间类型是为字符串，所以我设置了    sql.NullString     
SuccessTime     sql.NullString `db:"success_time" json:"success_time"`         // 成功时间
但是在插入的时候，你的sql语句出现了 多个字段 应该是解析的时候出了问题
`success_time`,`success_time.String`,`success_time.Valid`

**Comment by fifsky** [comment]
Hi @dmskys  原则上我们是不建议设计数据库的是时候设计允许NULL值的字段，这会让数据库查询、索引等变得更复杂更不可控，并且在Golang里面处理NULL值也非常繁琐，因此我们并没有打算支持sql.Null***

我在分支初步实现了支持sql.Null的示例，你可以参考一下
https://github.com/ilibs/gosql/blob/sqlnull/builder_test.go#L404

**Comment by dmskys** [comment]
@fifsky  是这样的 我的原则也是不允许设计null值，但是有一个订单处理的需求，比如用户提交了一个订单，这个时候这个订单有创建时间，create_time ，然后有一个管理员处理订单的时间 也叫成功时间， success_time 这个在创建订单的时候是需要为null，所以这种需求是存在的。希望你考虑一下完善

**Comment by fifsky** [comment]
@dmskys  感谢你的建议，确实是真实的业务场景，我们已经合并sql.Null功能到master，你可以更新试试，有问题随时反馈，谢谢

**Comment by dmskys** [comment]
@fifsky 非常感谢！ 有问题我会及时反馈，帮助你完善。
