### ISSUE TITLE
created_at字段为什么是UTC时间

### ISSUE THREAD

**Issue by athanxx** [ilibs/gosql#40]
我今天用了，字段里面有created_at还有updated_at
在win下调试，然后插入进去的是UTC时间，比正常时间少8小时，这个怎么调整？

**Comment by fifsky** [comment]
默认使用本地时区，所以需要查看本地时区是否正确

**Comment by athanxx** [comment]
我直接time.Now()是正确的，用了gosql打出来到数据库就不对了。不知道为啥

**Comment by athanxx** [comment]
找到原因，连接数据库时候要`&loc=Asia%2FShangha`·把这参数加上才不会错乱
