### ISSUE TITLE
能不能提供一个对外设置showsql的方法？

### ISSUE THREAD

**Issue by dmskys** [ilibs/gosql#6]
是这样的，我现在线上有一个需求是，默认的情况下，不显示sql语句，但是比如线上出了问题，我需要在不重启服务的情况下修改我本地的配置文件，监听配置文件变化改变你的showsql为true，监听本地配置文件变化，并获取新的配置文件我用的viper 这个配置库，所以能不能对外提供一个主动设置showsql的方法？

**Comment by fifsky** [comment]
@dmskys  其实你可以通过设置gosql.SetLogger 来接住SQL日志，然后想怎么处理显示不显示，还是监听配置显示都可以

我现在讲defaultLogger的SetLogging方法也对外暴露了，你可以动态开启默认Logger的日志

```go
gosql.SetLogging(true)
```

**Comment by dmskys** [comment]
你的gosql无法直接设置的SetLogger(true)，只能设置一个logger进去，但是这个logger又不是默认的logger 默认logger又不能访问
func SetLogger(l Logger) {
	logger.log = l
}

**Comment by dmskys** [comment]
好的 谢谢！
