### ISSUE TITLE
关于读写分离的小问题

### ISSUE THREAD

**Issue by Snowin1994** [ilibs/gosql#8]
gosql怎么支持读写分离呢，我注意到db链接是可以配置多个的，如何切换呢？

**Comment by dmskys** [comment]
@Snowin1994 gosql.Use(“dbname”)

**Comment by fifsky** [comment]
目前还不支持自动读写分离，需要自行决定连接读库还是写库，比如config["master"]  config["slave"] ，使用的时候
```
gosql.Use("slave")
```

**Comment by Snowin1994** [comment]
通过 ` gosql.Use(“dbname”)` 获取到的是一个Wrapper，之后就只能裸写sql来获取数据了？

**Comment by fifsky** [comment]
> 通过 `gosql.Use(“dbname”)` 获取到的是一个Wrapper，之后就只能裸写sql来获取数据了？

如果要使用Model，这里的确是不行的，因为Model是通过结构体的Db函数得到数据库连接实例，在我们的实际项目中读写分离是mysql proxy处理的，应用层本身是不关心的
